### ISSUE TITLE
New Arma Update big issue

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#439] opened 2016-09-22 17:59 UTC
it appears BI have broke wasteland, vehicles no longer move just crawl around

**Comment by AgentRev** [comment] 2016-09-22 18:01
¯\_(ツ)_/¯

**Comment by WhatsUpDoc127** [comment] 2016-09-22 18:10
Yep it happening on ALL A3Wasteland servers...Its only WHEELED vehicles this is happening with, not Tanks...Let me test the other vehicles such as APCs...

**Comment by WhatsUpDoc127** [comment] 2016-09-22 18:15
Confirm....its only WHEELED vehicles only...

**Comment by codexGW** [comment] 2016-09-22 18:18
Yep, boats are unaffected too but when I put a Strider in the water it was still affected (moving very very slow).

**Comment by ghost** [comment] 2016-09-22 18:23
yes wheeled vehicles only, do you think BI have fucked up the physics library or is this a wasteland issue ?

**Comment by WhatsUpDoc127** [comment] 2016-09-22 18:24
Its also in ALTIS so its not just TANOA...

**Comment by ghost** [comment] 2016-09-22 18:26
its all maps, even cup maps all of them.

**Comment by Soloknight** [comment] 2016-09-22 18:32
When I use Zeus to pick up the vehicle and drop it it goes up to 4mpg but still stuck in the ground

**Comment by Jermin** [comment] 2016-09-22 18:44
Yes. If you lift a quadbike and then put it back down, it's wheels ares still stuck. So it's not related to spawn height.

**Comment by Soloknight** [comment] 2016-09-22 19:01
Ai working fine in vehicles movement as usual, kill ai player cant move vehicle
got todo with player simulation maybe

**Comment by Soloknight** [comment] 2016-09-22 19:23
update, I use infistar to increase vehicle speed, its like brakes are always on a soon as I hit a hill and get air tires stop moving. hope this is helping

**Comment by biabock** [comment] 2016-09-22 21:29
ok... so seems the map markers bug is back either!
WTF BIS!??

**Comment by AgentRev** [comment] 2016-09-22 21:31
:joy:

**Comment by ghost** [comment] 2016-09-22 21:45
drawingInMap=0 seems to disable createMarker again

just disable it in your server.cfg

**Comment by biabock** [comment] 2016-09-22 22:11
yeah... drawingInMap=0 disable all map markers, even the client is not able to create one.
Just put that =1 and everything works "fine"...
thx matt

**Comment by hobart666** [comment] 2016-09-22 23:52
Big wheels keep on rollin'

**Comment by usszulu2** [comment] 2016-09-23 00:44
Ive noticed that when trying to drive a vehicle, the brake lights seem to stay on as if the brakes are on, and when trying to turn the wheel, you can't really turn it, the wheel just kinda shakes.

**Comment by MrNastyTime** [comment] 2016-09-23 01:10
Just had a player complete an Armed Convoy mission. He was able to drive the Armed Hunter around fine. Then I got in and tried to and it wouldn't budge. He then got in after me and was able to drive again just fine. Vehicle wasn't saved to him, just got it off a mission. I tried a Truck Convoy mission and the vehicles would not work for me. Just wanted to share.

**Comment by Soloknight** [comment] 2016-09-23 01:30
@MrNastyTime  Couldn't get it to work on my server. but if you notice when you get out of the vehicle the wheels keep turning left

**Comment by MrNastyTime** [comment] 2016-09-23 01:35
He even has a UGV Stomper that he can drive around. I tried that and it won't work for me. He tried some random spawned vehicles and he can't drive them. He mentioned when he got it the mission was still active. I just tried it and it wouldn't work for me. For whatever reason he is the only person so far I found that is able to drive a vehicle like that.

UPDATE: He's at the store right now and can drive any vehicle he buys or anyone else buys.

And I bought a UGV Stomper. I couldn't drive it if it was not moving. So I directed it somewhere and while moving when I took controls I could drive it normal.

UPDATE:

So I had this player who can drive disconnect from the server. When he comes back he is unable to drive vehicles anymore. Then, he goes and buys a UGV Stomper. Commands it to move somewhere and while moving takes controls and he can manually drive it himself. He then gets in the Passenger and then drives the stomper manually again from the UAV Terminal. Then he releases and ejects and now he can drives vehicles again. I tried to emulate it myself and I can't get it to work for me. But it is working for this guy.

We now have a second player that can drive after doing these steps. However, I was unable to get it to work for me. Hope some of this helps.

**Comment by usszulu2** [comment] 2016-09-23 02:55
For those of you that are depending on Email updates, MrNastyTime has been updating his post here https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/439#issuecomment-249077878 which I know doesn't generate updates.

**Comment by ghost** [comment] 2016-09-23 07:29
No luck Rev ?

**Comment by AgentRev** [comment] 2016-09-23 09:01
No time, unfortunately.

**Comment by Soloknight** [comment] 2016-09-23 11:52
There's a potential fix on the forms

**Comment by AgentRev** [comment] 2016-09-23 12:37
BIS or A3W? I will try to look at it this weekend, I'm stuck under a pile of physics homework atm

**Comment by DemonseedElite** [comment] 2016-09-23 13:22
@Soloknight Care to post a link?

**Comment by codexGW** [comment] 2016-09-23 13:25
http://forums.a3wasteland.com/index.php?topic=2999.msg17397#msg17397

**Comment by Soloknight** [comment] 2016-09-23 15:52
@DemonseedElite  Sorry was on my phone and driving to work. I was using voice to text as the reason I misspelled forums wrong ;) it was a3wasteland forums

**Comment by DemonseedElite** [comment] 2016-09-23 18:25
Thank you much!  This DOES work.  Just confirmed it on my server.  Just to echo the fix here:
Edit the file   \client\functions\playerSetupStart.sqf

change
{_player disableAI _x} foreach ["move","anim","target","autotarget"];

to

{_player disableAI _x} foreach ["anim","target","autotarget"];

i.e. Remove the string "move" from the array.  
Save, recompile to .pbo, restart server.

**Comment by ghost** [comment] 2016-09-23 18:48
That whole line is pointless imo, I believe it's from Tonics original Arma 2 wasteland code

**Comment by Jawshy** [comment] 2016-09-27 08:05
The `"PATH"` and `"MOVE"` values for the [`disableAI`](https://community.bistudio.com/wiki/disableAI) command have been fixed in version [1.65.138532](https://forums.bistudio.com/topic/140837-development-branch-changelog/page-44#entry3096805) (26-09-2016) [dev](https://dev.arma3.com/dev-branch). 

> Fixed: Using disableAI "PATH" and "MOVE" would not work correctly for vehicles driven by players (https://feedback.bistudio.com/T120346)

**Comment by Jawshy** [comment] 2016-10-15 04:27
[SPOTREP #00061](https://dev.arma3.com/post/spotrep-00061): 

> Fixed: Using disableAI "PATH" and "MOVE" would not work correctly for vehicles driven by players (https://feedback.bistudio.com/T120346)

**Closed as completed** 2018-04-14 00:48 UTC
