### ISSUE TITLE
0 vehicles loading

### ISSUE THREAD

**Issue by hobart666** [A3Wasteland/ArmA3_Wasteland.Altis#356] opened 2015-10-23 03:42 UTC
I'm having an issue over the last few days with saved vehicles loading, here are some errors I found in my .rpt file but oddly Ive checked both files against older missions I have and one vanilla one I just downloaded and those files are all the same. 

"A3Wasteland - world persistence loaded 150 objects from extDB"
"[extDB2] Sleep [4]: 54.21"
"[extDB2] Sleep [4]: 54.37"
"[extDB2] Sleep [4]: 54.49"
"[extDB2] Sleep [4]: 54.61"
"[extDB2] Sleep [4]: 54.73"
"[extDB2] Sleep [4]: 54.85"
Error in expression <0]],["450Rnd_127x108_B,[],0,0,0],[5887,"C_Quadbike_01_F",["21303.408203","16337.>
  Error position: <C_Quadbike_01_F",["21303.408203","16337.>
  Error Missing ]
Error in expression <0]],["450Rnd_127x108_B,[],0,0,0],[5887,"C_Quadbike_01_F",["21303.408203","16337.>
  Error position: <C_Quadbike_01_F",["21303.408203","16337.>
  Error Missing ]
Error in expression <ult = call compile _queryResult;

if ((_queryResult select 0) isEqualTo 0) exit>
  Error position: <_queryResult select 0) isEqualTo 0) exit>
  Error Undefined variable in expression: _queryresult
File mpmissions\__cur_mp.Altis\persistence\server\setup\extDB\async_database.sqf, line 63
Error in expression <
_vehicles pushBack _vehData;
} forEach _result;

_vehicles
>
  Error position: <_result;

_vehicles
>
  Error Undefined variable in expression: _result
File mpmissions\__cur_mp.Altis\persistence\server\world\extDB\getVehicles.sqf, line 65
"A3Wasteland - world persistence loaded 0 vehicles from extDB"
"WASTELAND SERVER - Initializing Server Spawning"

**Comment by thegoatman** [comment] 2015-10-23 09:35
I had this too Fix is quite simple:

UPDATE `servervehicles` SET `TurretMagazines` = '[]',`TurretMagazines2` = '[]', `TurretMagazines3` = '[]';

if you have phpmyadmin access to your database. The issue is caused by the infinite adding of magazines after restarts

**Comment by LouDnl** [comment] 2015-10-23 09:57
Hmm I don't have the not loading in vehicles error. But I do see an abundance of turretammo being saved. @AgentRev do you have a fix for this?

An "I_MRAP_03_F" has the following. Seems a bit much doesn't it?

[["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]],["Laserbatteries",[0]],["SmokeLauncherMag",[0]]]

**Comment by thegoatman** [comment] 2015-10-23 10:06
I am seeing the same only i already wiped all of it. So this is after 2 restarts for a kaiman
[["250Rnd_30mm_HE_shells_Tracer_Green",250],["8Rnd_LG_scalpel",8],["38Rnd_80mm_rockets",38],["250Rnd_30mm_HE_shells",250],["38Rnd_80mm_rockets",23],["8Rnd_LG_scalpel",8]]

**Comment by LouDnl** [comment] 2015-10-23 14:23
It's not the saving that causes this. I used your purge command which emptied the turret saves. Then after the first save runs the values are back so the conclusion is that the values are already stored ingame. There must be a bug with the game then?? Might be interesting to check this on a newly bought vehicle.

**Comment by thegoatman** [comment] 2015-10-23 14:29
I added setvehicleammo 0(or setvehicleammdef 0 cant remember which one was late last night) it seems to fix it a little only store bought vehicles had 0 ammo. Didnt have enough time to fully test it

**Comment by LouDnl** [comment] 2015-10-23 20:27
A newly bought Strider has:
22:22:12 [["200Rnd_127x99_mag_Tracer_Yellow",[0]],["200Rnd_127x99_mag_Tracer_Yellow",[0]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]]]

A strider that saved over 8 restarts has:
[["200Rnd_127x99_mag_Tracer_Yellow",[0]],["200Rnd_127x99_mag_Tracer_Yellow",[0]],["200Rnd_127x99_mag_Tracer_Yellow",[0]],["200Rnd_127x99_mag_Tracer_Yellow",[0]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]],["SmokeLauncherMag",[1]],["Laserbatteries",[1]

**Comment by hobart666** [comment] 2015-10-23 23:33
Thank you Goatman And Loud ( knew a guy nicknamed goatman in kentucky once lol) I'll try this right now. I have phpmyadmin and navicat (much easier & faster to use for most things). So just set these all to [] in the table?

**Comment by hobart666** [comment] 2015-10-24 20:26
That seemed to have worked but one issue I was having a bit back was with reincarnating vehicles upon restart. that has seemed to return. randomly of course!

**Comment by LouDnl** [comment] 2015-10-24 20:29
It only solves it for me untill the next save run.

**Comment by LouDnl** [comment] 2015-10-25 07:00
Could this be tied in with the lag and choke problem?

Verstuurd vanaf mijn iPhone

Op 24 okt. 2015 om 22:25 heeft hobart666 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


That seemed to have worked but one issue I was having a bit back was with reincarnating vehicles upon restart. that has seemed to return. randomly of course!

-

**Comment by LouDnl** [comment] 2015-10-25 19:46
Gonna try this for a while: https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/3ae26d513ad156149e87e6274ecf19ad58726aa5

**Comment by hobart666** [comment] 2015-10-25 21:45
I think it is big time after a few days of no lag choke but vehicle saving my lag just came back in the last 20 min. I'm going to delete them all in the db and see if the spikes happen. I will report back soon.

**Comment by LouDnl** [comment] 2015-10-26 20:38
Ok so after completely disabling saving and loading of vehicle and static ammo (vehicle turret ammo) etc. It seems the chokes are gone. But it's only been 2 restarts now. All vehicles spawn in with full ammo everytime atm.
Commits:
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/3ae26d513ad156149e87e6274ecf19ad58726aa5
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/abe5a0af0138b643c83a7ea5c3886ede460f543a
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/0f13eb5607c9baf36f2a62c88d9418fd89d837c7
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/51732cfea9e539ea5202d886a3e8bde5b6e029e1
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/e08c7345f3b1514b3fe5afb6c03295188ab5c214

**Comment by hobart666** [comment] 2015-10-27 00:26
did those changes do anything to beacons by chance? I'm not seeing any after I edited those.

**Comment by LouDnl** [comment] 2015-10-27 08:17
Not that I know of.

**Comment by hobart666** [comment] 2015-10-27 08:20
Confirmed earlier. Not getting any beacons saving after restart.

**Comment by LouDnl** [comment] 2015-10-27 08:30
It doesn't do anything to the beacons. Beacons load in fine on my mission and they save.

Load in after a restart:
[52117,"Land_TentDome_F",["21979.244141","21425.636719","0.621014"],[[-0.771362,0.636396,0],[0,0,1]],0,0,1,"76561197968317840",[["a3w_spawnBeacon",true],["R3F_LOG_disabled",true],["side","GUER"],["packing",false],["groupOnly",true],["ownerName",[76,111,117,68]]],[],[],[],[],[],0,0,0]

Save after a restart:
[09:28:41:569346 +02:00] [Thread 1096] extDB2: Input from Server: 1:559386:updateServerObject:52117:Class='"Land_TentDome_F"',Position='["21979.244141","21425.636719","0.621014"]',Direction='[[-0.771362,0.636396,0],[0,0,1]]',Damage=0,AllowDamage=1,OwnerUID='"76561197968317840"',Variables='[["a3w_spawnBeacon",true],["R3F_LOG_disabled",true],["side","GUER"],["packing",false],["groupOnly",true],["ownerName",[76,111,117,68]]]',Weapons='[]',Magazines='[]',Items='[]',Backpacks='[]',TurretMagazines='[]',AmmoCargo=0,FuelCargo=0,RepairCargo=0,Locked=0,Deployable=1
[09:28:41:569346 +02:00] [Thread 1096] extDB2: Output to Server: 
[09:28:41:569346 +02:00] [Thread 1176] extDB2: SQL_CUSTOM_V2: Trace: UniqueID: 1 Input: updateServerObject:52117:Class='"Land_TentDome_F"',Position='["21979.244141","21425.636719","0.621014"]',Direction='[[-0.771362,0.636396,0],[0,0,1]]',Damage=0,AllowDamage=1,OwnerUID='"76561197968317840"',Variables='[["a3w_spawnBeacon",true],["R3F_LOG_disabled",true],["side","GUER"],["packing",false],["groupOnly",true],["ownerName",[76,111,117,68]]]',Weapons='[]',Magazines='[]',Items='[]',Backpacks='[]',TurretMagazines='[]',AmmoCargo=0,FuelCargo=0,RepairCargo=0,Locked=0,Deployable=1
[09:28:41:580347 +02:00] [Thread 3516] extDB2: SQL_CUSTOM_V2: Trace: UniqueID: 1 Result: [1,[]]

**Comment by LouDnl** [comment] 2015-10-27 08:30
You must have made a typo somewhere.

**Comment by hobart666** [comment] 2015-10-27 14:25
Hmm wouldn't surprise me one bit. I'll go over it again.

**Comment by LouDnl** [comment] 2015-10-28 10:10
@AgentRev can you please have a look into this?

**Comment by AgentRev** [comment] 2015-10-28 11:19
I'm not sure what to do here. The problem is probably related to a change in the behavior of the magazinesAmmo command, but I can't pinpoint an accurate solution, and I'm very busy with college so I barely have the time to look at it.

**Comment by AgentRev** [comment] 2015-10-28 14:38
If Bohemia would bother to implement an `addMagazineAmmoTurret` command, I could probably fix this within a couple minutes.

**Comment by LouDnl** [comment] 2015-10-28 14:55
Well it's temporarily fixable when disabling all saving and loading of turretammo as done in my commits. This is just a frankenstein and no real fix.

**Comment by Gigatek1** [comment] 2015-10-28 15:41
I seems for A3Armory the only vehicles loading double ammo to turret 2 after restarts are MRAP_03_base_F. I did this as a temporary fix.
https://github.com/A3Armory/ArmA3_Wasteland.Altis/commit/4298def1d698479715c44f7ee6cd789453b09a5d
Looks like 1.52 bugged the MRAP_03_base_F

**Comment by AgentRev** [comment] 2015-10-31 23:54
Great, I was gonna convert the turret mag saving system to use the shiny new `magazinesAllTurrets` from v1.52, and Bohemia have yet proven again their spectacular ability to ship stuff that actually works!

\</sarcasm>

http://feedback.arma3.com/view.php?id=26398

**Comment by hobart666** [comment] 2015-10-31 23:56
Much love man!

**Comment by AgentRev** [comment] 2015-10-31 23:58
In other words, that shit broken and thus the fix cannot be made. Thanks Bohemia!

**Comment by hobart666** [comment] 2015-11-01 00:00
I kinda had that hunch all along. Big believer in not fixing things that
aren't broke. Too bad BIS doesn't have the same work ethic.

**Comment by AgentRev** [comment] 2015-11-01 00:49
Let's do a little recap:

* `magazines` - Made in 2006 - doesn't work properly for certain vehicles, doesn't return ammo
* `magazinesTurret` - Made in 2010 - works but requires turret path, doesn't return ammo
* `magazinesDetail` - Made in 2013 - doesn't work properly for certain vehicles
* `magazinesAmmo` - Made in 2013 - doesn't work properly for certain vehicles
* `magazinesAmmoFull` - Made in 2013 - doesn't work properly for certain vehicles
* `magazineTurretAmmo` - Made in 2013 - only returns info of first mag added instead of last added
* `magazinesAllTurrets` - Made in 2015 - doesn't work properly for certain vehicles

I don't even understand how and why I still hope they get their shit together at some point...

**Comment by LouDnl** [comment] 2015-11-01 10:37
Well that sucks. I've upvoted your ticket.

**Comment by LouDnl** [comment] 2015-11-05 08:57
Has anyone tried if this problem was fixed in perf8 yet so we can revert the non saving?

**Comment by AgentRev** [comment] 2015-11-05 12:26
It's not "fixable", they permanently altered the behavior of one of the commands listed above.

**Comment by LouDnl** [comment] 2015-11-05 12:28
[13:09:52] Thierry : Could you get this assigned? ttp://feedback.arma3.com/view.php?id=26398
[13:09:54] Thierry : http://feedback.arma3.com/view.php?id=26398
[13:10:12] David Foltyn: afaik it's already investigated
[13:10:20] Thierry : ohh status is still new
[13:18:47] David Foltyn: i mean the problem, not the ticket
[13:20:31] Thierry : ah ok thanks

**Comment by LouDnl** [comment] 2015-11-05 12:28
So atm all we can do is disable the turretammo saving untill they 'fix' it?

**Comment by AgentRev** [comment] 2015-11-05 12:28
Yes.

**Comment by LouDnl** [comment] 2015-11-05 12:30
Do you know which command they altered in which way?

**Comment by AgentRev** [comment] 2015-11-05 12:37
I'm not even sure. It could be setVehicleAmmo 0 no longer deleting empty mags, or magazinesTurret now returning empty mags, or it could be my shit code acting up. I haven't really investigated properly.

**Comment by AgentRev** [comment] 2015-11-05 12:39
Bottom line is this could get fixed entirely and instantly with a working magazinesAllTurrets and addMagazineAmmoTurret. I could just erase the whole code and rewrite it the way it should have been since the start.

**Comment by LouDnl** [comment] 2015-11-05 12:42
Tha's just hoping for christmas in june :)

**Comment by hobart666** [comment] 2015-11-10 02:44
upvoted the issue @ BIS as well. I am hoping for an early xmas but I know you have school man. so I'll just deal.

**Comment by thegoatman** [comment] 2015-11-15 11:03
It seems they have fixed the command: https://forums.bistudio.com/topic/140837-development-branch-changelog/?p=2933749

**Comment by AgentRev** [comment] 2015-12-29 04:45
I think this should do it: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/9beb8365f6739f9d46357c89c327b4af58397348

**Closed** 2016-03-16 07:03 UTC
Labels: fixed
